Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -44,13 +44,19 @@ jobs:
       run: |
         echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 
-    - name: Build and push Docker image
+    - name: Build and Push Docker image
       env:
         DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
       run: |
+        # Check if Dockerfile exists in the current directory
+        if [ ! -f Dockerfile ]; then
+          echo "Error: Dockerfile not found!"
+          exit 1
+        fi
+
         # Build the Docker image with the latest code
         docker build -t $DOCKER_REPOSITORY:latest .
-        
+
         # Push the Docker image to Docker Hub
         docker push $DOCKER_REPOSITORY:latest
 
